### PR TITLE
Fix share status when stopped.

### LINKED ISSUE #281: Share status is incorrect when node is stopped
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.1.0, core: 8.3.1, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v6.11.5
```

### Expected Behavior

When a share is stopped the node status should reset and Bridges should say disconnected.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
The peer status has the following problems:

1. Bridges set to  "connected".
2. The delta is still set.
3. Peers shows old count.
4. Uptime is still set.
5. Restarts count is still set.

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. stop a running share
2. run storjshare-status

Here is a screen shot:

### PR DESCRIPTION
**Pull request by him2him2**
close #281

I reset the share values when the share is stopped to the following:

1. Bridges set to  "disconnected".
2. The delta set to 0.
3. Peers set to 0.
4. Uptime set to 0ms.
5. Restarts count set to 0.

This should also fix similar problems in the GUI.

Here is a screen shot of the fix:

### CODE REVIEW

File: script/farmer.js [hunk 1]
```diff
@@ -66,7 +66,9 @@ farmer.on('bridgeChallenge', (bridge) => {
 farmer.on('bridgesConnected', function() {
   farmerState.bridgesConnectionStatus = 3;
 });
-
+farmer.on('bridgesDisconnected', function() {
```
Comment (braydonf) [inline script/farmer.js]: I don't think there is such an event name.

Comment (braydonf) [reply script/farmer.js]: I went ahead and removed this, and merged it.
